### ISSUE TITLE
Data fusion for Sentinel-5P and Sentinel-2

### ISSUE THREAD

**Issue by marcoruizrueda** [rodrigo-pena/sentinel-fusion#2]
Thanks for the code @rodrigo-pena Could you please give me some ideas on how to get fused data from Sentinel-2 and Sentinel-5P? I'm studying methane from TROPOMI and need to build a ML-dataset. Regards.

**Comment by rodrigo-pena** [comment]
Hi, @marcoruizrueda. It's been a while since I've been involved with this project, so I don't know how to answer your question. Maybe you could try writing an e-mail to somebody from Global Resource Information Database (GRID) - Geneva, team with which I worked with? They might be able to help, as they deal with satellite imaging on a regular basis.
